apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-csb-kubernetes
  namespace: csb-kubernetes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretadmin
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-csb-kubernetes
  namespace: csb-kubernetes
subjects:
- kind: ServiceAccount
  name: sa-csb-kubernetes
  namespace: csb-kubernetes
roleRef:
  kind: ClusterRole
  name: secretadmin
  apiGroup: rbac.authorization.k8s.io
