apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-csb-kubernetes
  namespace: sb-ocp-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: sb-ocp-secret
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-csb-kubernetes
  namespace: sb-ocp-secret
subjects:
- kind: ServiceAccount
  name: sa-csb-kubernetes
  namespace: sb-ocp-secret
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
